runtime: custom
env: flex

resources:
  cpu: 1
  memory_gb: 2.0
  disk_size_gb: 10

# Automatic scaling configuration
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cpu_utilization:
    target_utilization: 0.6

# Environment variables
env_variables:
  EXECUTION_MODE: "LIVE"
  # Keys should be set in GCP Secret Manager, but placeholders here
  GROWW_API_KEY: "MUST_BE_SET_IN_GCP" 
  
# Health check (Critical for survivability)
readiness_check:
  path: "/api/system/status"
  check_interval_sec: 60
  timeout_sec: 60
  failure_threshold: 4
  success_threshold: 2
  app_start_timeout_sec: 900 # 15 minutes max startup

liveness_check:
  path: "/api/system/status"
  check_interval_sec: 60
  timeout_sec: 60 # Allow 60s for ML inference to respond
  failure_threshold: 10 # Be very lenient
  success_threshold: 2
