runtime: custom
env: flex

resources:
  cpu: 1
  memory_gb: 2.0
  disk_size_gb: 10

network:
  forwarded_ports:
    - 8080/tcp

# Automatic scaling configuration
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cpu_utilization:
    target_utilization: 0.6

# Environment variables
env_variables:
  EXECUTION_MODE: "LIVE"
  # Keys should be set in GCP Secret Manager, but placeholders here
  GROWW_API_KEY: "MUST_BE_SET_IN_GCP" 
  
# Health check (Critical for survivability)
readiness_check:
  path: "/api/system/status"
  check_interval_sec: 30
  timeout_sec: 20
  failure_threshold: 4
  success_threshold: 2
  app_start_timeout_sec: 600

liveness_check:
  path: "/api/system/status"
  check_interval_sec: 60
  timeout_sec: 20
  failure_threshold: 4
  success_threshold: 2
